name: dart_builder
author: Matan Lurey <matanl@google.com>
description: A fluent API for creating Dart code.
version: 0.1.1
homepage: https://github.com/matanlurey/dart_builder
dependencies:
  dart_style: any
  mustache: any
  quiver: any
dev_dependencies:
  test: any
